---
title: "Reporte de Malaria, Colombia, 2019"
subtitle: (fuente SIVIGILA, Datos libres)
author: Zulma M. Cucunubá
output:
  pdf_document: default
  html_document: default
date: "2022-09-19"
---

```{r setup, echo=FALSE, error=FALSE, fig.height=5, fig.width=5, warning=FALSE, include = FALSE, message= FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(tidyverse)
library(ggspatial)
library(rgdal)
library(broom)
library(maptools)
library(data.table)
library(xml2)
library(httr)
library(config)


if (!require(gpclib)) 
    install.packages("gpclib", type = "source")
gpclibPermit()

rm(list = ls())
source("../R/read_data/import_data.R")
source("../R/read_data/scraping_data.R")
source("../R/debug_data/cleaning_data.R")
source("../R/debug_data/checking_data.R")
source("../R/analyticis_plotting/plotting.R")
source("../R/analyticis_plotting/build_endemic_channel.R")
```

## Reporte de Malaria en Colombia 2019

```{r leer_seleccionar, echo=FALSE, error=FALSE, fig.height=5, fig.width=5, warning=FALSE, include = FALSE, message= FALSE}
link_data <- "https://www.datos.gov.co/api/views/qvnt-2igj/rows.csv?accessType=DOWNLOAD"
sivigila_data <- import_sivigila_data(link_data)
filtered_data <- select_disease("MALAR", sivigila_data)

```

## Distribución de casos por semana epidemiológica


```{r inciencia, echo=FALSE, error=FALSE, fig.height=5, fig.width=10, warning=FALSE, include = TRUE, message= FALSE}

plot_epiweek(filtered_data, var_week = "SEMANA", var_cases = "conteo_casos", year = 2019, type = "date", xlabel = "Fecha de semana epidemiológica")

```

Distribución espacial de casos de malaria en Colombia

```{r map, echo=FALSE, error=FALSE, fig.height=8, fig.width=8, warning=FALSE, include = TRUE, message= FALSE}
deptos_data    <- import_sivigila_data("https://www.datos.gov.co/api/views/gdxc-w37w/rows.csv?accessType=DOWNLOAD")
deptos_data    <- get_depto_codes(deptos_data)
data_map_disease_deptos <- clean_depto_disease_codes(deptos_data, filtered_data)
map <- generate_dept_map_sivigila(data_map_disease_deptos, var_lj = "id")
map

```
## Canal endemico

```{r disease_data, echo=FALSE, error=FALSE, fig.height=5, fig.width=10, warning=FALSE, include=TRUE, message=FALSE}

#Import Data With Cache
disease_data <- import_data_disease_by_year(2018, "DENGUE")
disease_data_cache <- import_data_disease_by_year(2010, "DENGUE", cache = TRUE)
disease_data_use_cache <- import_data_disease_by_year(2010, "DENGUE", use_cache = TRUE)

#Canal endemico
year <- 2018
years_endemic_chanel <- c((year - 5):(year - 1))

disease_dt_by_week <- import_data_disease_by_year(year, "DENGUE", cache = TRUE)  %>% group_by_param("SEMANA")

for (y in years_endemic_chanel) {
    disease_dt_by_week <- import_data_disease_by_year(y, "DENGUE", cache = TRUE)  %>%  group_by_param("SEMANA") 
    disease_dt_by_week_y <- cbind(disease_dt_by_week, y_ = disease_dt_by_week$Casos)
}

#Distribución de casos por género y semana epidemiológica
disease_dt_by_gender_wk <- group_by_param(disease_data, "SEXO", "SEMANA", TRUE)
plot_by_parameter(disease_dt_by_gender_wk, var_x = "SEMANA", var_y = "Casos", var_fill = "SEXO", var_per = "Porcentaje", label_x = "Género", label_y = "Casos \n (Porcentajes)", scale_name = "Género", scale_labels = c("Femenino", "Masculino"), diagram_title = "Diagrama para la variable Sexo", legend_pos = "right", bar_wd = 1, text_sz = 1.2)

#Distribución de casos por género
disease_dt_by_gender <- group_by_param(disease_data, "SEXO", wt_percentage = TRUE)
plot_by_parameter(disease_dt_by_gender, var_x = "SEXO", var_y = "Casos", var_fill = "SEXO", var_per = "Porcentaje", label_x = "Género", label_y = "Casos \n (Porcentajes)", scale_name = "Género", scale_labels = c("Femenino", "Masculino"), diagram_title = "Diagrama para la variable Sexo", legend_pos = "right", bar_wd = 0.6, text_sz = 4)


#Distribución de casos por edades
disease_dt_by_age <- group_by_param(disease_data, "EDAD", "SEMANA", wt_percentage = TRUE)
disease_dt_by_age_range <- group_by_range(disease_data = disease_dt_by_age, "EDAD", min_val = 0, max_val = max(disease_dt_by_age$EDAD), 5)
plot_by_parameter(disease_dt_by_age_range, var_x = "EDAD", var_y = "Casos", var_fill = "EDAD",label_x = "Edad", label_y = "Casos \n (Porcentajes)", scale_name = "Edad", scale_labels = disease_dt_by_age_range$EDAD, diagram_title = "Diagrama para la variable Edad", legend_pos = "bottom", bar_wd = 0.7, text_sz = 3)

```
 